# IRON-GRID High Availability (Active-Passive)

config system ha
    set group-name "IRON-GRID-CLUSTER"
    set mode a-p                  # Active-Passive
    set hbdev "port3" 50          # Interface Heartbeat avec priorité
    set session-pickup enable     # Garde les sessions actives en cas de bascule
    set override disable
    set priority 200              # Le Master a la priorité la plus haute
    set monitor "port1" "port2"   # Surveille si un câble est débranché
end
