# IRON-GRID Remote Access VPN (IPsec)
# Uses LDAP for XAuth

config vpn ipsec phase1-interface
    edit "Remote-VPN"
        set type dynamic
        set interface "port1"
        set peertype any
        set psksecret ENC mysecretkey
        set authusrgrp "LDAP-Admins" # Ton groupe LDAP encore une fois !
    next
end
